import type { CodeLang } from "../hooks/useShiki.ts";

export interface Snippet {
    code: string;
    lang: CodeLang;
}

export interface PipelineStage {
    id: string;
    index: string;
    title: string;
    tag: string;
    summary: string;
    detail: string;
    bullets: string[];
    snippet: Snippet;
    accent: "fern" | "cyan" | "violet" | "amber";
}

export const PIPELINE_STAGES: PipelineStage[] = [
    {
        id: "parse",
        index: "01",
        title: "Schema load & parse",
        tag: "buildGraphQLSchemaFromString",
        summary: "SDL or introspection JSON in.",
        detail: "A GraphQL schema is declared in generators.yml — as SDL or as an introspection JSON dump. Fern detects the shape (by extension or content) and parses it into a GraphQLSchema. The workspace loader classifies a file as GraphQL by the `graphql:` key, not its extension, so .json works too.",
        bullets: [
            "SDL → buildSchema",
            "introspection JSON → buildClientSchema",
            "accepts { __schema } and { data: { __schema } }",
            "can sit alongside OpenAPI / AsyncAPI in one workspace"
        ],
        snippet: {
            lang: "json",
            code: `# generators.yml
api:
  - graphql: ./schema.graphql   # or ./schema.json
  - openapi: ./rest.yml          # optional — combined client`
        },
        accent: "cyan"
    },
    {
        id: "ir",
        index: "02",
        title: "GraphQL → Fern IR",
        tag: "@fern-api/graphql-to-fdr",
        summary: "Schema becomes the canonical IR.",
        detail: "The converter maps GraphQL onto the same intermediate representation every Fern generator consumes. Types, enums, unions, input objects, custom scalars, and @deprecated all translate. Each Query/Mutation/Subscription root field becomes a synthetic HTTP endpoint with a `graphql` transport carrying everything the runtime needs to rebuild queries.",
        bullets: [
            "convertGraphQLTypes → IR types + custom-scalar mapping",
            "convertRootFieldToEndpoint → HttpEndpoint(transport: graphql)",
            "transport: operationType, baked query, variableDefinitions, arguments",
            "@deprecated → IR availability; field args → graphqlFieldArguments"
        ],
        snippet: {
            lang: "typescript",
            code: `// each root field → a synthetic endpoint
{
  name: "post",
  transport: {
    type: "graphql",
    operationType: "query",
    query: "query Post($id: ID!) { post(id: $id) { ... } }",
    variableDefinitions: "$id: ID!",
    arguments: "(id: $id)"
  }
}`
        },
        accent: "fern"
    },
    {
        id: "merge",
        index: "03",
        title: "IR merge",
        tag: "generateIntermediateRepresentation",
        summary: "GraphQL ⊕ REST → one IR.",
        detail: "The GraphQL IR is attached as additionalIrs and merged inside the single function every generate path flows through. This is why a combined OpenAPI + GraphQL workspace yields ONE client. Auth is applied post-merge: a GraphQL schema can't express auth (it's just headers on the POST), so it's inherited from the surrounding API definition.",
        bullets: [
            "graphql IR attached as additionalIrs, merged at the chokepoint",
            "one client for REST + query/mutation/subscription",
            "applyAuthToGraphqlEndpoints flips auth on from the merged schemes",
            "auth comes from a combined spec or generators.yml — not the schema"
        ],
        snippet: {
            lang: "typescript",
            code: `// post-merge: honor declared auth on graphql endpoints
if (ir.auth.schemes.length > 0) {
  for (const endpoint of graphqlEndpoints(ir)) {
    endpoint.auth = true; // queries, mutations & subscriptions
  }
}`
        },
        accent: "violet"
    },
    {
        id: "emit",
        index: "04",
        title: "TypeScript generation",
        tag: "generators/typescript",
        summary: "The only language-specific stage.",
        detail: "From here it's an ordinary Fern generator consuming IR. The GraphQL-shaped layer adds typed selection, selection-inferred result types, grouped client namespaces, a paginate.* namespace, the small core/graphql runtime, and autogenerated README sections — all on top of Fern's existing auth/retries/base-URL/fetch infrastructure.",
        bullets: [
            "<Type>Select types + Result<Model, S> selection inference",
            "client.query.* / client.mutation.* / client.subscription.*",
            "paginate.* async iterators (root + nested connections)",
            "core/graphql runtime + autogenerated README sections"
        ],
        snippet: {
            lang: "typescript",
            code: `const { data } = await client.query.post(
  { id: "post-1" },
  { id: true, title: true, author: { name: true } },
);
// data is typed to exactly the fields you selected`
        },
        accent: "amber"
    }
];

export interface Feature {
    title: string;
    blurb: string;
    snippet: Snippet;
}

export const FEATURES: Feature[] = [
    {
        title: "Typed field selection",
        blurb: "Choose exactly which fields come back. The result type narrows to match — unselected fields are absent, not undefined.",
        snippet: {
            lang: "typescript",
            code: `const { data } = await client.query.post(
  { id },
  { id: true, title: true },
);`
        }
    },
    {
        title: "Selection-inferred output",
        blurb: "Result<Model, S> is a mapped type that derives the response shape from your selection at compile time.",
        snippet: {
            lang: "typescript",
            code: `// data: { id: string; title: string }
// (no body, author, viewCount — you didn't ask)`
        }
    },
    {
        title: "{ data, errors } envelope",
        blurb: "GraphQL is partial-success. Operations return both data and errors; opt into throwing with throwOnError.",
        snippet: {
            lang: "typescript",
            code: `const { data, errors } = await client.query.post(args, sel);
const strict = await client.query.post(args, sel, {
  throwOnError: true,
});`
        }
    },
    {
        title: "Relay auto-pagination",
        blurb: "Connections expose async iterators under paginate.* that follow pageInfo.endCursor — including connections nested under a root field.",
        snippet: {
            lang: "typescript",
            code: `for await (const node of client.query.paginate.siteProducts(
  { first: 50 },
  { entityId: true, name: true },
)) {
  console.log(node);
}`
        }
    },
    {
        title: "Typed subscriptions",
        blurb: "Subscription operations stream over graphql-transport-ws as a typed AsyncIterableIterator. Auth-aware; breaking the loop tears down the socket.",
        snippet: {
            lang: "typescript",
            code: `for await (const event of client.subscription.onMessage(
  { roomId },
  { id: true, text: true },
)) {
  console.log(event);
}`
        }
    },
    {
        title: "raw() escape hatch",
        blurb: "Power users send a hand-written document and get the same envelope back, reusing the SDK's auth, retries, and base URL.",
        snippet: {
            lang: "typescript",
            code: `const { data } = await client.raw<{ order: { id: string } }>(
  \`query ($id: ID!) { order(id: $id) { id } }\`,
  { id: "order-123" },
);`
        }
    },
    {
        title: "__on / __args / __all",
        blurb: "Inline fragments for unions and interfaces, arguments on nested fields, and __all to take every scalar at a level.",
        snippet: {
            lang: "typescript",
            code: `{
  __on: { Image: { url: true }, Video: { duration: true } },
  comments: { __args: { first: 10 }, __all: true },
}`
        }
    },
    {
        title: "Custom scalars & deprecations",
        blurb: "DateTime/UUID/Long map to primitives, JSON to unknown, unknown scalars to string. @deprecated becomes @deprecated JSDoc.",
        snippet: {
            lang: "typescript",
            code: `type Json = unknown;        // scalar JSON
type DateTime = string;     // ISO-8601
/** @deprecated use displayName */
username?: string;`
        }
    },
    {
        title: "Combined REST + GraphQL",
        blurb: "One client, one auth story. REST endpoints sit next to query / mutation / subscription namespaces.",
        snippet: {
            lang: "typescript",
            code: `await client.orders.list();          // REST
await client.query.post({ id }, sel); // GraphQL`
        }
    }
];

export interface ComparisonRow {
    aspect: string;
    rest: string;
    graphql: string;
}

export const VS_OPENAPI: ComparisonRow[] = [
    { aspect: "Response type", rest: "Fixed, declared response model", graphql: "Result<Model, S> narrowed to your selection" },
    { aspect: "Field selection", rest: "N/A — server decides the shape", graphql: "Caller-driven, typed selection" },
    { aspect: "Error model", rest: "Throws a typed API error", graphql: "{ data, errors } envelope (throwOnError to throw)" },
    { aspect: "Pagination", rest: "On-method (.page() / cursor helpers)", graphql: "Separate paginate.* namespace, async iterators" },
    { aspect: "Streaming", rest: "SSE / response streams", graphql: "Subscriptions over graphql-transport-ws" },
    { aspect: "Method layout", rest: "Tagged by resource / subpackage", graphql: "Grouped under query / mutation / subscription" },
    { aspect: "Shared foundation", rest: "IR + runtime: auth, retries, base URL, docs, publishing", graphql: "Same IR + same runtime — thin GraphQL layer on top" }
];

export interface ToolComparison {
    name: string;
    kind: string;
    note: string;
    fernEdge: string;
}

export const VS_TOOLS: ToolComparison[] = [
    {
        name: "graphql-code-generator",
        kind: "Codegen (you author operations)",
        note: "GraphQL-native and powerful, but you write the operations and wire plugins; TypeScript-first.",
        fernEdge: "Generates the client surface from the schema alone — plus multi-language, docs & publishing."
    },
    {
        name: "genql",
        kind: "Schema-driven codegen",
        note: "Closest in spirit — selection inference like Result<T, S>.",
        fernEdge: "Adds the platform: combined REST+GraphQL, auth/retries runtime, docs, other languages."
    },
    {
        name: "Apollo Client / urql",
        kind: "Runtime clients",
        note: "Caching & state runtimes, not code generators.",
        fernEdge: "Produces a typed, publishable per-API SDK from the schema."
    },
    {
        name: "Vendor SDKs (e.g. Shopify)",
        kind: "Hand-maintained per language",
        note: "Bespoke, costly to keep in sync across languages.",
        fernEdge: "Generated from the schema — stays in sync and spans languages from one source."
    }
];

export const LANGUAGES: { name: string; status: "done" | "next" }[] = [
    { name: "TypeScript", status: "done" },
    { name: "Python", status: "next" },
    { name: "Go", status: "next" },
    { name: "Java", status: "next" },
    { name: "C#", status: "next" }
];
